name: Docker React CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run React Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t subash/docker-react -f Dockerfile.dev .

      - name: Run test
        uses: docker run -e CI=true subash/docker-react npm run test